#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

SQUID_KEYDIR="${SQUID_KEYDIR:-/etc/squid}";
SQUID_HTPASSWDFILE="${SQUID_HTPASSWDFILE:-$KEYDIR/.htpasswd}";
WEBADMIN=${WEBADMIN:-admin};
PASSWORD=${PASSWORD:-insecurebydefault};

if [ -z "${SQUID_NO_HTPASSWD}" ]; # i.e. no need for htpasswd
then
    mkdir -p \
        $(dirname $SQUID_HTPASSWDFILE) \
        ;

    if [ -f "${SQUID_HTPASSWDFILE}" ];
    then
        vecho "Using .htpasswd found in ${SQUID_HTPASSWDFILE}";
    else
        vecho "Generating ${SQUID_HTPASSWDFILE}";
        vecho "Adding credentials for ${WEBADMIN}";
        htpasswd -bcB "${SQUID_HTPASSWDFILE}" "${WEBADMIN}" "${PASSWORD}";
    fi;
    chown ${S6_USER:-alpine}:${S6_USER:-alpine} \
        $(dirname $SQUID_HTPASSWDFILE) \
        $SQUID_HTPASSWDFILE \
        ;
    chmod 400 $SQUID_HTPASSWDFILE;
# else
#     vecho "Not generating .htpasswd";
fi;

