#!/usr/bin/with-contenv bash
set -e

SQUID_CONFDIR="${SQUID_CONFDIR:-/etc/squid}";
SQUID_ARGS="${SQUID_ARGS:- -NYCd 5}";

exec \
    /usr/sbin/squid \
    -f ${SQUID_CONFDIR}/squid.conf \
    ${SQUID_ARGS} \
    ;
