#!/usr/bin/with-contenv bash

if [ ! -f /etc/squid/squid.conf ];
then
	echo "Using default config";
	cp -rv /defaults/squid/* /etc/squid/;
fi;

chown squid:squid \
    /var/cache/squid;

chmod ugo+w \
    /dev/stdout \
    /dev/stderr;

[[ ! -d /var/cache/squid/00 ]] && \
    /usr/sbin/squid -Nz -f /etc/squid/squid.conf;

