#!/usr/bin/with-contenv bash

KEYDIR="/etc/squid";

ADMIN=${WEBADMIN:-admin}
PASSWORD=${PASSWORD:-insecurebydefault}

if [ -f ${KEYDIR}/.htpasswd ];
then
    echo "using .htpasswd found in ${KEYDIR}";
else
    echo "generatign .htpasswd in ${KEYDIR}";
    echo "adding credentials: ${ADMIN}/${PASSWORD}";
    htpasswd -bcB ${KEYDIR}/.htpasswd ${ADMIN} ${PASSWORD}
fi;

